# Generated by Django 3.1.7 on 2021-03-18 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('salutation', models.CharField(choices=[('Mr.', 'Mister'), ('Ms.', 'Mistress')], default='Mr.', max_length=3)),
                ('designation', models.CharField(choices=[('AO', 'Assistant Officer'), ('O', 'Officer'), ('MTO', 'Management Trainee Officer'), ('SO', 'Senior Officer')], default='', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
