# Generated by Django 3.1.7 on 2021-05-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210418_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='office_id',
            field=models.IntegerField(default=6465),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(choices=[('AO', 'Assistant Officer'), ('O', 'Officer'), ('MTO', 'Management Trainee Officer'), ('SO', 'Senior Officer')], default='', max_length=6),
        ),
    ]
