# Generated by Django 3.1.7 on 2021-03-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210318_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder_time',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
