# Generated by Django 3.1.7 on 2021-03-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210318_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder_time',
            field=models.DateTimeField(),
        ),
    ]
